### ISSUE TITLE
make[3]: *** [MP_boolean.lo] Error 1

### ISSUE THREAD

**Issue by naghmeh6** [coin-or/COIN-OR-OptimizationSuite#11]
I am trying to compile Coin-or on my Mac 
with this command
        
                         `make -j 2;`

I get this error:

```
3 warnings and 1 error generated.
make[3]: *** [MP_boolean.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
2 warnings and 1 error generated.
make[3]: *** [MP_constant.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by tkralphs** [comment]
A lot more information would be needed to know what the problem is here. I couldn't begin to guess from the above. In any case, this looks like a failure in the build of [CoinMP](https://github.com/coin-or/CoinMP), so it should be reported there. If you are using `coinbrew` to build and don't need CoinMP, you can simply add `--skip=CoinMP` to the command line or comment it out in the `Dependencies` file.
